# Site settings
title: "Abraham Levine"
email: alevine@hhai.org
description: "Abraham Levine's school website"
baseurl: "http://alevhhai.github.io"
title_description: "Hey! I'm Abraham. I write code, make glitch art, sometimes (poorly) make music, and listen to too much music."
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
post_limit: 5

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
