# Site settings
title: Abraham Levine
email: alevine@hhai.org
description: Abraham Levine's school website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alevhhai.github.io" # the base hostname & protocol for your site
github_username:  arcetera

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# Build settings
markdown: kramdown

